### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Mstrodl** [shoghicp/BigBrother#27]
this happens whenever I log in:

> 16:28:47 [INFO] MStrodl[/172.16.0.12:50012] logged in with entity id 1 at (world, 128, 66, 128)
> 16:28:47 [CRITICAL] Could not execute task > Callback#shoghicp\BigBrother\DesktopPlayer::bigBrother_authenticationCallback: Undefined offset: 1
> 16:28:47 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in  "/BigBrother_v1.4.0-beta.phar/src/shoghicp/BigBrother/DesktopPlayer" at line 176
> 16:28:47 [CRITICAL] Could not tick level world: Undefined offset: 1

and freezes all commands and disables login for others until the pc client disconnects I'm using the latest version of pocketmine dev and your plugin thanks in advance @shoghicp  also happy birthday!

**Comment by shoghicp** [comment]
This issue is duplicated

**Comment by cloud9350** [comment]
Use Windows.
This BigBrother plugin is NOT working for Linux.
