### ISSUE TITLE
Update for 0.11.0?

### ISSUE THREAD

**Issue by HBIDamian** [shoghicp/BigBrother#46]
Basically, although this version ( 1.5 beta ) was ment for 0.10.5, i went ahead and tried for the 0.11.0 server, and, as you may know, it doesn't work. 
[CRITICAL] [BigBrother] Couldn't find a protocol translator for #27, disabling plugin
Im just wondering if you are going to carry on with this project throughout 0.11.0 too?

**Comment by shoghicp** [comment]
This needs an upgrade for every protocol update, please don't use the bug tracker for suggestions or feature requests
