### ISSUE TITLE
When it will support MCPE 0.14.0?

### ISSUE THREAD

**Issue by MasterWolf** [shoghicp/BigBrother#50]

**Comment by alex2534alex** [comment]
Как по мне, этого не произойдёт. Ты видел когда в последний раз разраб что-то здесь делал? :\
I think never((

**Comment by MasterWolf** [comment]
@alex2534alex тож так думаю... очень жаль...

**Comment by xZeroMCPE** [comment]
No, try [BungeeCordPE](https://www.github.com/BukkitPE/BungeeCordPE)

**Comment by MasterWolf** [comment]
@AndreTheGamer is it as same as BigBrother?

**Comment by xZeroMCPE** [comment]
@MasterWolf Yea

**Comment by MasterWolf** [comment]
@AndreTheGamer  ok can you plz tell me how to use it? I want to join my mcpe server from pc. Can i do it with this plugin?

**Comment by xZeroMCPE** [comment]
@MasterWolf  I can't tell you it on here, But i can help you on BungeeCordPE repo. If i do help you here that would be advertising...ect)

**Comment by MasterWolf** [comment]
@AndreTheGamer ok i will go to repo

**Comment by xZeroMCPE** [comment]
@MasterWolf  don't forget to close this issue ;)
