### ISSUE TITLE
Received encoded string buffer length is longer than maximum...

### ISSUE THREAD

**Issue by va2ron1** [shoghicp/BigBrother#53]
Hi! I've been making changes to this plugin and I really stuck here... 
Repo: https://github.com/va2ron1/BigBrother

Log:
![screen shot 2016-07-06 at 12 04 07 am](https://cloud.githubusercontent.com/assets/303179/16607333/a404b190-430d-11e6-99db-224ed602633f.png)

Problem:
![screen shot 2016-07-06 at 12 01 29 am](https://cloud.githubusercontent.com/assets/303179/16607283/42e2e2e2-430d-11e6-8b04-36246a050068.png)

**Comment by MrDoni98** [comment]
same problem

**Comment by va2ron1** [comment]
Check out the update, works again (Not properly). The player shows in the Pocket Edition but the PC edition can't see the players from PE also the player can't move, but is progress.
