### ISSUE TITLE
0.17?

### ISSUE THREAD

**Issue by remotevase** [shoghicp/BigBrother#58]
Out soon, somebody plz update!

**Comment by Saxavlax001** [comment]
Bigbrother for now I think its dead.

**Comment by matthew4444** [comment]
were trying to. but my friends are in compleyty differebnt time zones, ;(

**Comment by matthew4444** [comment]
as in our fork of this plugin

**Comment by remotevase** [comment]
Oh great!

**Comment by Fudster** [comment]
I have a alternative. 

windows 10:  [Minecraft: Pocket Edition](https://www.microsoft.com/en-us/store/p/minecraft-windows-10-edition/9nblggh2jhxjl)

Have the PC version of minecraft? [Cool. Get Minecraft: Pocket Edition for windows 10  free here](https://mojang.com/2015/07/get-minecraft-windows-10-edition-beta-for-free/l)

**Comment by matthew4444** [comment]
No

**Comment by Saxavlax001** [comment]
Make plugin support mcpe 1.0

**Comment by matthew4444** [comment]
were trying , but since were all in different time zones, theres not much that can be done, but we only have one more packet to fix, but no progress so far after that. srry, if i can get any help, with fixing the update-block-packet , the project would bd done, we made it work with pc, but the block update packet, discconcts the pc client , can anyone help plz, and soory anout that . :(

**Comment by matthew4444** [comment]
is there a way to fix this bug?
1. Fix server not reciveing player packets(meaning player cant place or break blocks):

Notice: Uninitialized string offset: 19 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110
[Receive from MatthewJP] 0x8

**Comment by remotevase** [comment]
idk

**Comment by matthew4444** [comment]
kk

**Comment by remotevase** [comment]
wait when did I become a collaborator?

**Comment by remotevase** [comment]
Awesome!

**Comment by remotevase** [comment]
wait never mind im not

**Comment by Fudster** [comment]
Not sure why you guys thumbed down my comment.

The windows 10 app is the EXACT app.

So using the windows 10 app you can connect to PE servers on windows 10.

**Comment by matthew4444** [comment]
I use bluestacks android emulator

**Comment by matthew4444** [comment]
to play mcpe on pc

**Comment by matthew4444** [comment]
:)

**Comment by matthew4444** [comment]
its free :)

**Comment by Saxavlax001** [comment]
matthew4444,use the packets from fork of va2ron,idk know from developing plugins,but this maybe help you.idk

**Comment by Saxavlax001** [comment]
https://github.com/va2ron1/BigBrother

**Comment by Saxavlax001** [comment]
He tried to make big brother support 0.15

**Comment by remotevase** [comment]
Hmm... Okay

**Comment by MalakasPlayzMC** [comment]
https://github.com/BigBrotherTeam/BigBrother


Please close
